name: Run BBP Scraper Every 4 Hours

on:
  schedule:
    - cron: "0 */4 * * *"  # Runs every 2 hours
  workflow_dispatch:       # Allow manual trigger from GitHub UI

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    env:
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
      FROM_EMAIL: ${{ secrets.FROM_EMAIL }}
      FROM_EMAIL_PASSWORD: ${{ secrets.FROM_EMAIL_PASSWORD }}
      TO_EMAIL: ${{ secrets.TO_EMAIL }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Install dependencies
      run: go mod tidy

    - name: Build
      run: go build -v ./...

    - name: Run BBP Scraper
      run: go run .
